### ISSUE TITLE
No licensing information

### ISSUE THREAD

**Issue by hce** [singpolyma/wai-session-clientsession#4]
Just noticed by doing "stack list-dependencies --license" that your package does not supply licensing information. Could you add that?

**Comment by singpolyma** [comment]
https://github.com/singpolyma/wai-session-clientsession/blob/master/COPYING

**Comment by hce** [comment]
Well. When running "stack list-dependencies --license --no-include-base" your packages do not include correctly the licensing information.

Example excerpt:

[...]
wai-extra MIT
wai-logger BSD3
wai-session OtherLicense
wai-session-clientsession OtherLicense
wai-session-postgresql BSD3
wai-websockets MIT
[...]

**Comment by singpolyma** [comment]
It's right there in the list: `OtherLicense` (namely ISC, but cabal doesn't know how to report ISC last I checked)

**Comment by hce** [comment]
Well, "OtherLicense" is of little meaning to someone wishing to catalogue all the licenses of all their dependencies ;-)

**Comment by singpolyma** [comment]
Looks like ISC may have been added to newer versions of Cabal. I'll have to check that it works with all the versions I support, but it might be possible to list it in the metadata now (though if you are very worried about dependency licenses you should *never* trust the metadata and always check the real license at least).
